#!/usr/bin/env python3
#A script to dedent noweb code.
#When writing noweb documents, I like to indent code chunks, for ease of reading.
#But this ought to be stripped out before use.
#This script strips shared leading whitespace from noweb chunks.
#Reads from stdin, writes to stdout.

from textwrap import dedent
from sys import stdin
import re

chunk = ""

for line in stdin:
	#Included files will need dedenting, so their names will need changing.
	line = re.sub("child=\"(.*).rnw\"", "child=\"\\1-dedented.rnw\"", line)
	#knitr sometimes seems to struggle with tabs, so turn them to four spaces.
	line = line.replace("\t", "    ")
	#Chunks start with a line containing only <<something>>= or @
	#Each can be followed by whitespace
	if re.match("^<<.*>>= *$", dedent(line)) or re.match("^@ *$", dedent(line)):
		print(dedent(chunk), end="")
		chunk = ""
		print(dedent(line), end="")
	else:
		chunk += line

print(dedent(chunk), end="")
